name: Block Merge Based on Time
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  block:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - uses: yykamei/block-merge-based-on-time@37e89da846e881a30a0790691ca2967d3c8592b3 # main
        id: block
        with:
          timezone: Asia/Tokyo
          after: 03:00
          before: 04:00
      - env:
          PR_BLOCKED: ${{ steps.block.outputs.pr-blocked }}
        run: echo "pr-blocked=$PR_BLOCKED"
        if: github.event_name == 'pull_request'
