name: GitHub Workflows Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
permissions:
  actions: read
  issues: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/github-workflows-metrics@ee4cc54ed556a638ebd9151d077d502c94980c0e # main
        with:
          status: "success"
          aggregate: average
